server:
  port: 2001  #端口
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                       #增加服务自动通过服务名来调用服务
          lowerCaseServiceId: true            #开启小写的服务名称进行访问  http://网关/服务名称(小写)/**
      routes:
      - id: server-demo
        uri: lb://server-demo                #lb表示去注册中心获取服务
        predicates:
        - Path=/server-demo/**               #设置请求的路径规则
eureka:
  instance:
    prefer-ip-address: true                   #采用IP注册
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port} # Eureka Web 控制台查看服务注册信息的时候，就是这样的一个格式:user-PC:service-user: 8081 可以修改为 service-user:192.168.10.170:8081
    lease-renewal-interval-in-seconds: 10     #默认30  eureka client 发送心跳给eureka server的频率
    lease-expiration-duration-in-seconds: 60  #默认90 Eureka Server至上一次收到client 的心跳之后， 等待下一次心跳的超时时间 在这个时间内若没收到下一次心跳，则移除该 Instance
  client:
    service-url:
      defaultZone: http://alpha:123456@localhost:8761/eureka/ #注册中心的地址
    healthcheck:
      enabled: true                            #开启健康检查
