version: "1"
services:
 eureka-server:
  build: ./eureka-server
  image: wrecked/eureka-server:latest
  restart: on-failure
  ports:
	- 8761:8761
  deploy:
	replicas: 1
	restart_policy:
	  condition: on-failure