version: "3.7"
services:
 eureka-server:  #服务名
   build: ./eureka-server/   #服务Dockerfile 目录
   image: wrecked/eureka-server:latest  #指定镜像名称或者镜像id
   restart: on-failure  #
   ports:
    -  8761:8761
 zuul-server:
   build: ./zuul-server/
   image: wrecked/zuul-server:latest
   restart: on-failure  #指定容器退出后的重启策略为始终重启。该命令对保持服务始终运行十分有效，在生产环境中推荐配置为 always 或者 unless-stopped
   ports:
    -  2002:2002
   depends_on:       #解决容器的依赖、启动先后的问题
    - eureka-server
 config-server:
   build: ./config-server/
   image: wrecked/config-server:latest
   restart: on-failure
   ports:
    - 8888:8888
   depends_on:
    - eureka-server
 server-demo:
   build: ./server-demo/
   image: wrecked/microservice-orderservice:latest
   restart: on-failure
   ports:
    - 8081:8081
   depends_on:
    - eureka-server
    - config-server
 monitoring-server:
   build: ./monitoring-server/
   image: wrecked/microservice-userservice:latest
   restart: on-failure
   ports:
    - 9091:9091
   depends_on:
    - eureka-server